# Generated by Django 5.0.2 on 2024-02-21 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='children',
        ),
        migrations.RemoveField(
            model_name='family',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='familygarden',
            name='trees',
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='child_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='parent_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familygarden',
            name='trees',
            field=models.ManyToManyField(blank=True, related_name='family_gardens', to='family.familytree'),
        ),
    ]
