# Generated by Django 5.0.2 on 2024-02-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_remove_family_children_remove_family_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygarden',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familygarden',
            name='family_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
