# Generated by Django 5.0.2 on 2024-02-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='images',
        ),
        migrations.AddField(
            model_name='family',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='family_preview/'),
        ),
        migrations.CreateModel(
            name='FamilyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='family_images/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='family.family')),
            ],
        ),
    ]
